config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#index"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/mens", to: "products#mens"
    get "/womans", to: "products#womans"
    get "sort", to: "categories#category_sort"
    devise_for :users
    resources :users, except: :destroy
    resources :account_activations, only: %i(edit create)
    resources :password_resets, except: %i(destroy index show)

    namespace :admin do
      get "search", to: "products#index"
      resources :static_pages
      resources :categories
      resources :orders
      resources :products
      resources :users
      resources :banners
      root "static_pages#index"
    end
    resources :ratings
    resources :order_details
    resources :categories do
      member do
        get :filter
      end
    end
    resources :products do
      collection do
        get :result
      end
    end
    resources :carts
    resources :orders do
      member do
        get :change
      end
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  acts_as_paranoid without_default_scope: true
  enum status: {Pending: 0, Shipping: 1, Delivered: 2, Canceled: 3,
                Rejected: 4}, _default: 0

  ORDER_ATTRS = %w(quantity price product_id amount phone).freeze

  has_many :order_details, dependent: :destroy
  has_many :products, through: :order_details

  belongs_to :user, optional: true

  delegate :name, to: :user

  scope :oldest, ->{order created_at: :asc}
  scope :by_user, ->(uid){where user_id: uid}

  scope :most_order, (lambda do
    Order.Delivered.group(:user_id)
                    .order("count_all DESC").limit(1).count.first.first
  end)

  scope :order_by_price, ->(criteria){order(price: criteria)}
  scope :this_month, (lambda do
    where(created_at:
      DateTime.now.beginning_of_month..DateTime.now.end_of_month)
  end)

  private

  def update_branch
    case status
    when "Shipping", "Delivered"
      order_details = self.order_details
      order_details.each do |order_detail|
        product = order_detail.product
        product.quantity_in_stock -= order_detail.quantity
        product.update!(quantity_in_stock: product.quantity_in_stock)
      end
    when "Rejected", "Canceled"
      order_details = self.order_details
      order_details.each do |order_detail|
        product = order_detail.product
        product.quantity_in_stock += order_detail.quantity
        product.update!(quantity_in_stock: product.quantity_in_stock)
      end
    end
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController
  before_action :find_order, only: %i(edit update)

  def index
    @orders = Order.without_deleted.oldest
    @pagy, @orders2  = pagy(Order.oldest,
                            items: Settings.order.item)
  end

  def edit
    @order_details = @order.order_details
  end

  def update
    if @order.update(order_params)
      update_branch @order.status
      redirect_to admin_orders_path
    else
      flash[:danger] = t "flashes.update_failed"
      render :edit
    end
  end

  private
  def find_order
    @order = Order.find_by id: params[:id]
    return if @order

    flash[:danger] = t "flashes.alert_not_found"
    redirect_to admin_orders_path
  end

  def order_params
    params.require(:order).permit(:user_id, :amount, :status)
  end

  def update_branch status
    case status
    when "Shipping", "Delivered"
      order_details = @order.order_details
      order_details.each do |order_detail|
        product = order_detail.product
        product.quantity_in_stock -= order_detail.quantity
        product.update!(quantity_in_stock: product.quantity_in_stock)
      end
    when "Rejected", "Canceled"
      order_details = @order.order_details
      order_details.each do |order_detail|
        product = order_detail.product
        product.quantity_in_stock += order_detail.quantity
        product.update!(quantity_in_stock: product.quantity_in_stock)
      end
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  #before_action :authenticate_user!, only: %i(new create)
  before_action :current_cart, :load_product_in_cart
  before_action :check_product_quantity, only: %i(new create)

  def index
    @pagy, @orders = pagy current_user.orders
  end

  def new
    if !current_user.nil?
      @order = current_user.orders.build
    elsif !params[:phone].blank?
      @order = Order.new
      @order.phone = params[:phone]
    else
      flash[:danger] = "Phone number is required"
      redirect_to request.referrer
    end
    @product = Product.find_by id: params[:id]
  end

  def create
    if current_user.nil?
      @order = Order.new order_params
      @order.phone = params[:order][:phone]
      @name = params[:order][:name] unless params[:order][:name].blank?
    else
      @order = current_user.orders.new order_params
    end
    if @order.valid?
      create_transaction
    else
      flash.now[:danger] = t ".order_fail"
      render :new
    end
  end

  def destroy
    @order = Order.find params[:id]
    if @order.destroy
      flash[:success] = t "static_pages.delete_success"
      redirect_to action: :index
    else
      flash[:danger] = t "static_pages.delete_fail"
    end
  end

  def change
    @order = Order.find_by(id: params[:id]).Canceled!
    if @order
      flash[:success] = t "static_pages.change_success"
    else
      flash[:danger] = t "static_pages.change_fail"
    end
    redirect_to request.referer
  end

  private
  def order_params
    params.require(:order).permit Order::ORDER_ATTRS
  end

  def create_order_detail
    @products.each do |item|
      product_id = item.id.to_i
      @order.order_details.create!(
        product_id: product_id,
        quantity: @carts[product_id.to_s],
        price: item.price
      )
    end
  end

  def create_transaction
    ActiveRecord::Base.transaction do
      @order.save!
      create_order_detail
      clear_carts
      redirect_to root_path
      flash[:success] = t ".success_checkout"
    end
  rescue StandardError
    flash[:danger] = t ".danger_checkout"
    redirect_to carts_path
  end
end

app/helpers/admin/order_helper.rb
module Admin::OrderHelper
  def style_status status
    case status
    when "Pending"
      class_type = "info"
    when "Shipping"
      class_type = "primary"
    when "Delivered"
      class_type = "success"
    when "Canceled"
      class_type = "warning"
    when "Rejected"
      class_type = "danger"
    end
    sanitize "<div class='btn btn-#{class_type}'>#{status}</div>"
  end

  def options_for_status current_status
    case current_status
    when "Pending"
      %w(Shipping Rejected)
    when "Shipping"
      %w(Delivered Canceled)
    else
      []
    end
  end

  def can_change? current_status
    if (current_status == "Rejected") ||
       (current_status == "Canceled") || (current_status == "Delivered")
      false
    else
      true
    end
  end
end

app/views/admin/orders/_form.html.erb
<div class = "category-index-padding">
  <div class = "container">
    <div class="card">
      <div class="card-header">
        <h1><%= t "admin.order.details" %><%= @order.id %></h1>
      </div>
      <div class="card-body">
        <%= form_for [:admin, @order] do |form| %>
        <div class="field">
          <h3>
          <%= form.label t("admin.order.current_status") %>
          <%= style_status(@order.status) %>
          </h3>
        </div>

        <% if can_change?(@order.status) %>
        <div class="control-group">
          <%= form.label t("admin.order.update_status"), class: "control-label" %>
          <div class="col-sm-2">
            <%= form.select :status, options_for_status(@order.status), {}, class: "form-select form-select" %>
          </div>
        </div>
        <% end %>

        <table class = "table table-striped">
          <thead>
            <tr>
              <th><%= t "admin.order.quantity" %></th>
              <th><%= t "admin.order.price" %></th>
              <th><%= t "admin.order.name" %></th>
            </tr>
          </thead>

          <tbody>
            <% @order_details.includes([:product]).each do |order_detail| %>
              <tr>
                <td><%= order_detail.quantity %></td>
                <td><%= order_detail.price %></td>
                <td><%= order_detail.name %></td>
              </tr>
            <% end %>
          </tbody>
      </table>

        <div class="field">
          <h4>
            <%= form.label t("admin.order.total") %>
            <%= @order.amount %>
          </h4>
        </div>

        <% if can_change?(@order.status) %>
          <div class="actions">
            <div style = "submit_padding"><%= form.submit t("submit"), class: "btn btn-success", data: { confirm: t("admin.category.you_sure") } %></div>
          </div>
        <% end %>
        <br>
        <%= link_to t("admin.category.back_index"), admin_orders_path, class: "btn btn-primary" %>
        <%= link_to t("admin.category.back_user"), admin_user_path(@order.user), class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/_order.html.erb
<tr>
  <td><%= order.id %></td>
  <td><%= order.name %></td>
  <td><%= order.created_at.strftime(Settings.order.date_format) %></td>
  <td><%= order.amount %></td>
  <td><%= style_status(order.status) %></td>
  <td class = "td_custom"><%= link_to icon("fa regular", "eye"), edit_admin_order_path(order) %></td>
</tr>

app/views/admin/orders/edit.html.erb
<%= render "form", order: @order%>

app/views/admin/orders/index.html.erb
<div class = "category-index-padding">
  <div class = "container">
    <div class="card">
      <div class="row">
        <div class="col text-center">
          <div class="card">
            <div class="card text-white bg-info">
              <div class="card-header">
                <h5><%= t "admin.order.pending" %></h5>
              </div>
              <div class="card-body">
                <h3><%= @orders.Pending.size %></h3>
              </div>
            </div>
          </div>
        </div>
        <div class="col text-center">
          <div class="card">
            <div class="card text-white bg-primary">
              <div class="card-header"><h5><%= t "admin.order.shipping" %></h5></div>
              <div class="card-body">
                <h3><%= @orders.Shipping.size %></h3>
              </div>
            </div>
          </div>
        </div>
        <div class="col text-center">
          <div class="card">
            <div class="card text-white bg-success">
              <div class="card-header"><h5><%= t "admin.order.delivered" %></h5></div>
              <div class="card-body">
                <h3><%= @orders.Delivered.size %></h3>
              </div>
            </div>
          </div>
        </div>
        <div class="col text-center">
          <div class="card">
            <div class="card text-white bg-warning">
              <div class="card-header"><h5><%= t "admin.order.canceled" %></h5></div>
              <div class="card-body">
                <h3><%= @orders.Canceled.size %></h3>
              </div>
            </div>
          </div>
        </div>
        <div class="col text-center">
          <div class="card">
            <div class="card text-white bg-danger">
              <div class="card-header"><h5><%= t "admin.order.rejected" %></h5></div>
              <div class="card-body">
                <h3><%= @orders.Rejected.size %></h3>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <br>

  <div class = "container">
    <div class="card">
      <div class="card-header">
        <h1><%= t "admin.order.orders" %></h1>
      </div>
      <div class="card-body">
        <table class = "table table-striped">
          <thead>
            <tr>
              <th><%= t "admin.order.id" %></th>
              <th><%= t "admin.order.customer" %></th>
              <th><%= t "admin.order.date" %></th>
              <th><%= t "admin.order.amount" %></th>
              <th><%= t "admin.order.status" %></th>
              <th><%= t "admin.order.action" %></th>
            </tr>
          </thead>

          <tbody>
            <%= render @orders2.includes([:user]) %>
          </tbody>
        </table>
        <%== pagy_bootstrap_nav(@pagy) %>
      </div>
    </div>
  </div>
</div>