config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#index"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/mens", to: "products#mens"
    get "/womans", to: "products#womans"
    get "sort", to: "categories#category_sort"
    devise_for :users
    resources :users, except: :destroy
    resources :account_activations, only: %i(edit create)
    resources :password_resets, except: %i(destroy index show)

    namespace :admin do
      get "search", to: "products#index"
      resources :static_pages
      resources :categories
      resources :orders
      resources :products
      resources :users
      resources :banners
      root "static_pages#index"
    end
    resources :ratings
    resources :order_details
    resources :categories do
      member do
        get :filter
      end
    end
    resources :products do
      collection do
        get :result
      end
    end
    resources :carts
    resources :orders do
      member do
        get :change
      end
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category, optional: true
  has_many :ratings, dependent: :destroy
  has_many :order_details
  has_many :orders, through: :order_details
  has_many :product_images, dependent: :destroy, inverse_of: :product
  acts_as_paranoid without_default_scope: true

  accepts_nested_attributes_for :product_images, allow_destroy: true

  delegate :name, to: :category, prefix: true

  validates :price, :quantity_in_stock, presence: true

  scope :mens, ->{where("products.category_id IN (?)", [3,5,7,9])}

  scope :womans, ->{where("products.category_id IN (?)", [4,6,8,10,11])}

  scope :by_name, (lambda do |name|
                     where("name LIKE (?)", "%#{name}%") if name.present?
                   end)
  scope :order_by_price, ->(criteria){order(price: criteria)}
  scope :find_category_id, ->(param){where category_id: param}
  scope :order_by_created_at, ->(param){order(created_at: param)}
  scope :newest, ->{order created_at: :desc}
  scope :oldest, ->{order created_at: :asc}
  scope :by_ids, ->(ids){where id: ids}
  scope :uncategorized, ->{where category_id: nil}
  scope :by_category, ->(category_id){where category_id: category_id}
  scope :cheapest, ->{order price: :asc}
  scope :most_expensive, ->{order price: :desc}
  scope :categorized, ->{where.not(category_id: nil)}

  def find_root_category parent_path
    arr = parent_path.split("/")
    return arr.second
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  before_action :find_product, only: %i(edit show update destroy)
  before_action :get_categories, only: %i(new edit show update index)

  def index
    filter_branch params
  end

  def show
    @product.product_images.build
  end

  def new
    @product = Product.new
    @product.product_images.build
  end

  def edit; end

  def update
    if @product.update(product_params)
      flash[:success] = t "flashes.update_success"
      redirect_to admin_product_path(@product)
    else
      flash[:danger] = t "flashes.update_failed"
      render :edit
    end
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = t "flashes.create_success"
      redirect_to admin_product_path(@product)
    else
      flash[:danger] = t "flashes.create_failed"
      render :new
    end
  end

  def destroy
    if @product.destroy
      flash[:success] = t "flashes.delete_success"
    else
      flash[:danger] = t "flashes.delete_failed"
    end
    redirect_to admin_products_path
  end

  private
  def find_product
    @product = Product.without_deleted.categorized.find_by id: params[:id]
    return if @product

    flash[:danger] = t "flashes.alert_not_found"
    redirect_to admin_products_path
  end

  def product_params
    params.require(:product).permit(:name, :price, :description,
                                    :quantity_in_stock, :category_id,
                                    product_images_attributes:
                                    [:id, :image, :_destroy])
  end

  def get_categories
    @categories = Category.all
  end

  def filter_branch params
    if params[:filter] == t("admin.product.filter.uncate")
      @pagy, @products = pagy(Product.without_deleted.uncategorized,
                              items: Settings.product.item)
    elsif params[:name].present?
      @pagy, @products = pagy(Product.without_deleted.where("name like ?", "%#{params[:name]}%"),
        items: Settings.product.item)
    else
      @pagy, @products = pagy(Product.without_deleted.newest,
                              items: Settings.product.item)
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include ProductsHelper

  before_action :current_visitor_selections

  def index
    @q = Product.without_deleted.categorized.ransack(params[:q])
    unless !@q.result.empty?
      flash[:danger] = "Can't find what you look for"
      redirect_to root_path
      return
    end
    @pagy, @products = pagy @q.result
  end

  def mens
    @search = Product.without_deleted.categorized.mens.ransack(params[:q])
    @pagy, @products = pagy @search.result
  end

  def womans
    @search = Product.without_deleted.categorized.womans.ransack(params[:q])
    @pagy, @products = pagy @search.result
  end

  def show
    visitor_selection(params[:id])
    @product = Product.without_deleted.categorized.find_by(id: params[:id])
    @ratings = Rating.where(product_id: params[:id])
    if current_user.present?
      @rating = current_user.ratings.build
    end
    if @product.present?
      @ratings_stats = @ratings if @ratings.present?
      @pagy, @ratings = pagy @ratings if @ratings.present?

      @same_category = @product.category.products.where.not(id: params[:id]).sample(10)
    end
    return if @product.present?

    flash[:danger] = t "static_pages.product_not_found"
    redirect_to root_path
  end

  def result
    @name = params[:name]
    @pagy, @products = pagy Product.without_deleted.categorized.by_name params[:name]
  end

  def all_product(category_id)
  end

  private

  def visitor_selection(pid)
    session[:selection] ||= []

    if !session[:selection].include? pid.to_i
      session[:selection].unshift pid.to_i
    end
  end
end

app/helpers/admin/product_helper.rb
module Admin::ProductHelper
  def category_name category_id
    category = @categories.find_by id: category_id
    category.nil? ? t("admin.category.none") : category.name
  end

  def in_category categories
    output = []
    categories.each do |cate|
      input = [cate.name, cate.id.to_s]
      output.append input
    end
    output.append ["None", ""]
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def average_star(ratings)
    sum = 0
    count = 0
    ratings.each do |rating|
      sum += rating.star.to_i
      count += 1
    end
    return sum / count
  end

  def star_statistic(ratings)
    arr = [0, 0, 0, 0, 0, 0]
    sum = 0
    ratings.each do |rating|
      case rating.star
      when 1
        arr[0] += 1
      when 2
        arr[1] += 1
      when 3
        arr[2] += 1
      when 4
        arr[3] += 1
      when 5
        arr[4] += 1
      end
      sum += rating.star
    end
    arr[5] = sum / ratings.size
    return arr
  end

  def current_visitor_selections
    session[:selection] ||= []
    @selections = session[:selection]
  end

  def allow_comment(product)
    allow = false
    product.orders.each do |order|
      if order.user_id == current_user.id
        allow = true
        break
      end
    end
    return allow
  end

  def checkout_these_product(dataset)
    session[:selection] ||= []
    recommend_pids = []
    if !current_user.nil?
      if dataset == 1 and !current_user.recommend_1.nil?
        recommend_pids = eval(current_user.recommend_1)
      elsif dataset == 2 and !current_user.recommend_2.nil?
        recommend_pids = eval(current_user.recommend_2)
      elsif dataset == 3 and !current_user.recommend_3.nil?
        recommend_pids = eval(current_user.recommend_3)
      end
    end

    if session[:selection].present?
      rules = Recommended.all
      rules.each do |rule|
        if rule.dataset == dataset.to_s
          associations = rule.associations.split("=>").map! { |id| id.to_i }
          left = []
          left << associations.first
          check = session[:selection] - left
          if check != session[:selection]
            second = []
            second << associations.second
            recommend_pids = (recommend_pids + second).uniq
          end
        end
      end
    end

    if session[:selection].present?
      session[:selection].each do |pid|
        products = Product.categorized.without_deleted.find_by(id: pid).category.products.sample(2).pluck(:id)
        recommend_pids << products
        recommend_pids.flatten!
        recommend_pids.uniq!
        if recommend_pids.size >= 15
          break
        end
      end
    end
    #-----------------------------------------------------------------------------------
    # if recommend_pids.size > 15
    #   recommend_pids = recommend_pids.take(15)
    # end
    if recommend_pids.size < 15
      take_num = 15 - recommend_pids.size
      extras = Product.categorized.without_deleted.sample(take_num).pluck(:id)
      recommend_pids << extras
    end
    recommend_pids.flatten!
    return recommend_pids
  end

  def categories_of_woman
    cate_w = []
    Category.all.each do |cate|
      if cate.parent_path.present?
        if cate.parent_path.split("/").second.to_i == 2
          cate_w << cate
        end
      end
    end
    return cate_w
  end

  def page_path current_product
    page_path = ["Homepage"]
    product_category = current_product.category.id
    parent_category = current_product.category.category.name
    page_path << parent_category << product_category
    return page_path
  end
end

app/views/admin/products/_form.html.erb
<%= form_for [:admin, @product], :html=> {:multipart => true} do |f| %>
  <div class="row">
    <div class="column">
      <div class="form-outline mb-4">
        <%= f.label :name, class:"form-label"%>
          <%= f.text_field :name, type: "text" , id: "form4Example1" , class: "form-control" %>
      </div>

      <div class="form-outline mb-4">
        <%= f.label :price, class:"form-label"%>
          <%= f.text_field :price, type: "text" , id: "form4Example1" , class: "form-control" %>
      </div>

      <div class="form-outline mb-4">
        <%= f.label :quantity_in_stock, class:"form-label"%>
        <%= f.text_field :quantity_in_stock, type: "text" , id: "form4Example1" , class: "form-control" %>
      </div>

      <div class="form-outline mb-4">
        <%= f.label t("admin.category.parent"), class: "control-label" %>
          <div class="control-group">
            <%= f.select(:category_id, in_category(@categories)) %>
          </div>
      </div>
    </div>
    <div class="column">
      <div class="form-outline mb-4">
        <%= f.label :description %>
          <%= f.text_area :description, class: "form-control" , id: "form4Example3" , rows: "2" %>
      </div>

      <div class="form-outline mb-4">
        <div>
          <%= f.fields_for :product_images do |pimg| %>
            <%= render "product_image_fields" , f: pimg %>
          <% end %>
          <div class="links">
            <%= link_to_add_association t("add_image") , f, :product_images,
              class: "btn btn-outline-success" %>
          </div>
        </div>
      </div>
      <%= f.submit t("submit"), class: "btn btn-primary btn-block mb-4", data: { confirm: t("admin.category.you_sure") } %>
    </div>
  </div>
<% end %>

app/views/admin/products/_images.html.erb
<% if product.product_images.any? %>
  <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <% product.product_images.includes(image_attachment: :blob).each do |proimg| %>
        <% if proimg == product.product_images.first %>
          <div class="carousel-item active">
            <strong><%= t("admin.product.image") + product.product_images.find_index(proimg).to_s %></strong>
            <%= image_tag((proimg.image), class: "d-block w-100") if proimg.image.present?%>
          </div>
        <% elsif proimg == product.product_images.last %>
          <% break %>
        <% else %>
          <div class="carousel-item">
            <strong><%= t("admin.product.image") + product.product_images.find_index(proimg).to_s %></strong>
            <%= image_tag(proimg.thumbnail(proimg.image), class: "d-block w-100") if proimg.image.present?%>
          </div>
        <% end %>
      <% end %>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
<% end %>

app/views/admin/products/_product.html.erb
<tr>
  <td><%= product.name %></td>
  <td><%= product.price %></td>
  <td><%= product.quantity_in_stock %></td>
  <td><%= category_name(product.category_id) %></td>
  <td><%= link_to icon("fa regular", "eye"), admin_product_path(product) %>
  <%= link_to icon("fa regular", "pen-to-square"), edit_admin_product_path(product), class: "td_custom" %>
  <%= link_to icon("fa regular", "trash"), admin_product_path(product), method: :delete, data: { confirm: t("admin.product.you_sure") } %>
  </td>
</tr>

app/views/admin/products/_product_image_fields.html.erb
<div class="nested-fields">
  <%= f.label :image %>
  <%= f.file_field :image %><br>
  <div class = "remove_image">
    <%= link_to_remove_association t("admin.product.remove images"), f, class: "btn btn-outline-danger"%>
  </div>
</div>

app/views/admin/products/_search_form.html.erb
<%= form_tag(admin_search_path, method: "get") do %>
  <div class="wrapper">
    <div class="first-third">
      <%= link_to t("admin.product.new_product"), new_admin_product_path, class: "btn btn-outline-success", style: "min-width: 20%" %>
    </div>
    <div class="second-third">
      <%= select_tag "filter" , options_for_select([
                t("admin.product.filter.select") ,
                t("admin.product.filter.newest") ,
                t("admin.product.filter.uncate") ]), class: "form-select form-select" %>
    </div>
    <div class="third-third">
      <%= submit_tag t("submit"), class: "btn btn-primary" %>
    </div>
  </div>
</div>
<% end %>

app/views/admin/products/edit.html.erb
<div class="category-index-padding">
  <div class = "container">
    <div class="card">
      <div class="card-body">
        <%= render "form", product: @product %>
        <%= link_to t("admin.product.show"), admin_product_path(@product), class: "btn btn-outline-primary" %>
        <%= link_to t("admin.product.back"), admin_products_path, class: "btn btn-outline-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/index.html.erb
<div class="category-index-padding">
  <div class = "container">
    <div class="card">
      <div class="card-header">
        <h1><%= t "admin.product.products" %></h1>
      </div>
      <div class="card-body">
        <div class="wrapper">
          <%= form_tag(admin_products_path, method: "get", class: "form-group") do %>
            <%= text_field_tag "name", nil, class: "form-control", style: "display: inline; width: 20%;" %>
            <%= submit_tag "Search", class: "btn btn-primary" %>
          <% end %>
        </div>
        <br>
        <%= render "search_form" %>
        <% if @products.empty? %>
          <h3>NO DATA</h3>
        <% else %>
        <table class = "table table-striped">
          <thead>
            <tr>
              <th><%= t "admin.product.name" %></th>
              <th><%= t "admin.product.price" %></th>
              <th><%= t "admin.product.quantity_in_stock" %></th>
              <th><%= t "admin.product.category" %></th>
              <th><%= t "admin.category.content" %></th>
            </tr>
          </thead>
          <tbody>
            <%= render @products %>
          </tbody>
        </table>
        <%== pagy_bootstrap_nav(@pagy) %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class="category-index-padding">
  <div class = "container">
    <div class="card">
      <div class="container">
        <div class="card-header">
          <h1><%= t "admin.product.new" %></h1>
        </div>
        <div class="card-body">
          <%= render "form" %>
          <%= link_to t("admin.product.back"), admin_products_path, class: "btn btn-outline-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/show.html.erb
<div class="category-index-padding">
  <div class="container">
    <div class="card mb-3">
      <div class="card-header" style="background: none">
        <h2>
          <%= @product.name %>
        </h2>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-sm-6">
            <div class="card text-white bg-info mb-3">
              <div class="card-body ">
                <h5 class="card-title">
                  <%= t("admin.product.id_field") + @product.id.to_s %>
                </h5>
                <strong>
                  <p class="card-text">
                    <%= t("admin.product.name") + @product.name %>
                  </p>
                  <p class="card-text">
                    <%= t("admin.product.price") + @product.price.to_s %>
                  </p>
                  <p class="card-text">
                    <%= t("admin.product.category") + ": " + @product.category_name %>
                  </p>
                  <p class="card-text">
                    <%= t("admin.product.quantity") + @product.quantity_in_stock.to_s %>
                  </p>
                  <p class="card-text">
                    <% if @product.description.present? %>
                      <%= t("admin.product.description") + @product.description %>
                    <% end %>
                  </p>
                </strong>
              </div>
            </div>
          </div>
          <div class="col-sm-6">
            <div class="card mb-3" style="text-align: center">
              <div class="card-body">
                <%= render "images", product: @product %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <%= link_to t("admin.product.edit"), edit_admin_product_path(@product), class: "btn btn-primary"%>
    <%= link_to t("admin.product.back"), admin_products_path, class: "btn btn-primary" %>
  </div>
</div>