config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#index"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/mens", to: "products#mens"
    get "/womans", to: "products#womans"
    get "sort", to: "categories#category_sort"
    devise_for :users
    resources :users, except: :destroy
    resources :account_activations, only: %i(edit create)
    resources :password_resets, except: %i(destroy index show)

    namespace :admin do
      get "search", to: "products#index"
      resources :static_pages
      resources :categories
      resources :orders
      resources :products
      resources :users
      resources :banners
      root "static_pages#index"
    end
    resources :ratings
    resources :order_details
    resources :categories do
      member do
        get :filter
      end
    end
    resources :products do
      collection do
        get :result
      end
    end
    resources :carts
    resources :orders do
      member do
        get :change
      end
    end
  end
end

app/controllers/admin/static_pages_controller.rb
class Admin::StaticPagesController < Admin::BaseController
  def index
    @q = Product.ransack(params[:q])
    @products = Product.group(:category_id).count
    @orders = Order.group(:user_id).count
    @order_details = OrderDetail.group(:product_id).count
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  include StaticPagesHelper
  include ProductsHelper
  $count = 0
  $check = 0
  $recommendations
  @@most_viewed

  def index
    @banners = Banner.all

    if $check == 0
      @@most_viewed = Recommended.most_viewed
      if @@most_viewed.nil?
        @@most_viewed = Product.sample(4)
      end
      @products = @@most_viewed.take(4)
    else
      @products = @@most_viewed.take(4)
    end
    $check = 1

    if $count == 0
      recommends = checkout_these_product 2
      $recommendations = get_product_array(recommends)
    end

    if $count < 2
      $count += 1
    else
      $count = 0
    end

    @best_sellings = best_sellings
    @order_details = OrderDetail.this_month.group(:product_id).count.to_a.sort_by(&:last).reverse!.take(4)
  end

  def mens
    @category = Category.find_by(id: 1)
    product_list = []
    @category.categories.each do |cate|
      cate.products.each do |product|
        product_list << product
      end
    end
    @pagy, @products = pagy product_list
  end

  def womans
    @categories = Category.womans
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  include Pagy::Backend

  def pagy_products(category_id)
    @pagy, @products = pagy(Product.categorized.without_deleted.find_category_id(category_id), items: Settings.product.item)
  end

  def recommend_for_you
    if !session[:selection].nil?
      @recomends = []
      product_list = session[:selection]
      product_list.map! { |p| p.to_i }

      session_associations = []
      associations = Recommended.last(2)
      associations.each do |a|
        pids = a.associations.split("-")
        pids.map! { |id| id.to_i }
        session_associations = (session_associations + pids).uniq
      end
    end
  end

  def get_product_array(recommends)
    product_arr = []
    recommends.each do |rec|
      begin
        p = Product.categorized.without_deleted&.find(rec)
      rescue
        next
      end
      if p.present?
        product_arr << p
      end
    end
    return product_arr
  end

  def best_sellings
    if OrderDetail.any?
      products = OrderDetail.group(:product_id).order("count_all DESC").count.keys
      return Product.without_deleted.categorized.where(id: products).take(4)
    end
  end
end

app/views/admin/static_pages/_content.html.erb
<div id="layoutSidenav">
  <div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
      <div class="sb-sidenav-menu">
        <div class="nav">
          <div class="sb-sidenav-menu-heading"><%= t "admin.static_pages.main" %></div>
          <%= link_to admin_root_path, class: "nav-link", :action => 'get' do %>
            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
            <%= t "admin.static_pages.dashboard" %>
          <% end %>
          <div class="sb-sidenav-menu-heading"><%= t "admin.static_pages.manage" %></div>
          <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts"
              aria-expanded="false" aria-controls="collapseLayouts">
            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
            <%= t "admin.static_pages.tables" %>
            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
          </a>
          <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
            <nav class="sb-sidenav-menu-nested nav">
              <%= link_to t("admin.static_pages.category"), admin_categories_path, class: "nav-link" %>
            </nav>
            <nav class="sb-sidenav-menu-nested nav">
              <%= link_to t("admin.order.orders"), admin_orders_path, class: "nav-link" %>
            </nav>
            <nav class="sb-sidenav-menu-nested nav">
              <%= link_to t("admin.product.products"), admin_products_path, class: "nav-link" %>
            </nav>
            <nav class="sb-sidenav-menu-nested nav">
              <%= link_to t("admin.user.users"), admin_users_path, class: "nav-link" %>
            </nav>
          </div>
          <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages"
              aria-expanded="false" aria-controls="collapsePages">
            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
            <%= t "admin.static_pages.communicate" %>
            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
          </a>
          <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
            <nav class="sb-sidenav-menu-nested nav">
              <%= link_to "Banner", admin_banners_path, class: "nav-link" %>
            </nav>
          </div>
          <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages"
              aria-expanded="false" aria-controls="collapsePages">

            <%= link_to root_path, class: "nav-link" do %>
            <div class="sb-nav-link-icon">
              <%= icon("fa regular", "bag-shopping") %>
              </div>
              <%= t("static_pages.user_page") %>

            <% end %>
          </a>
        </div>
      </div>
    </nav>
  </div>
  <div id="layoutSidenav_content">
    <main>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %> alert_mess"><%= message %></div>
      <% end %>
      <%= yield %>
    </main>
  </div>
</div>

app/views/admin/static_pages/_sidebar.html.erb
<div id="layoutSidenav">
  <div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
      <div class="sb-sidenav-menu">
        <div class="nav">
          <div class="sb-sidenav-menu-heading"><%= t "admin.static_pages.main" %></div>
          <a class="nav-link" href="index.html">
            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
            <%= t "admin.static_pages.dashboard" %>
          </a>
          <div class="sb-sidenav-menu-heading"><%= t "admin.static_pages.manage" %></div>
          <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts"
            aria-expanded="false" aria-controls="collapseLayouts">
            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
            <%= t "admin.static_pages.tables" %>
            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
          </a>
          <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
            <nav class="sb-sidenav-menu-nested nav">
              <%= link_to t("admin.static_pages.category"), admin_categories_path, class: "nav-link" %>
            </nav>
          </div>
          <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages"
            aria-expanded="false" aria-controls="collapsePages">
            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
            <%= t "admin.static_pages.communicate" %>
            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
          </a>
          <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
            <nav class="sb-sidenav-menu-nested nav">
              <a class="nav-link" href="layout-static.html"><%= t "admin.static_pages.email" %></a>
            </nav>
          </div>
          <div class="sb-sidenav-menu-heading"><%= t "admin.static_pages.statistic" %></div>
          <a class="nav-link" href="charts.html">
            <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
            <%= t "admin.static_pages.charts" %>
          </a>
        </div>
      </div>
      <div class="sb-sidenav-footer">
        <div class="small"><%= t "admin.static_pages.logged_in_as" %></div>
      </div>
    </nav>
  </div>
    <div id="layoutSidenav_content"></div>
  </div>
</div>

app/views/admin/static_pages/_topnav.html.erb
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
  <!-- Navbar Brand-->
  <%= link_to "Admin Ecommerce" , admin_root_path, :class=> "navbar-brand ps-3"%>
    <!-- Sidebar Toggle-->
    <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i
        class="fas fa-bars"></i></button>

    <div class="translate">
      <%= link_to "English", locale: :en %>
      <%= link_to "Vietnamese", locale: :vi %>
    </div>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
      <div class="input-group"></div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown"
          aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
          <li><%= link_to t("admin.static_pages.settings"), "#", class: "dropdown-item" %></li>
          <li>
            <hr class="dropdown-divider" />
          </li>
          <li><%= link_to t("admin.static_pages.log_out"), destroy_user_session_path,  method: :delete, class: "dropdown-item" %></li>
        </ul>
      </li>
    </ul>
</nav>

app/views/admin/static_pages/index.html.erb
<div class="container-fluid px-4">
  <h1 class="mt-4"><%= t "admin.static_pages.name"%></h1>
  <ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active"><%= t "admin.static_pages.main"%></li>
  </ol>
  <div class="row">
    <div class="col-xl-3 col-md-6">
      <div class="card bg-primary text-white mb-4">
        <div class="card-body"><%= t "admin.static_pages.product"%></div>
          <div class="card-footer d-flex align-items-center justify-content-between">
            <%= link_to t("admin.static_pages.view_details"), admin_products_path, class: "small text-white stretched-link"%>
          <div class="small text-white"><i class="fas fa-angle-right"></i></div>
        </div>
      </div>
    </div>
    <div class="col-xl-3 col-md-6">
      <div class="card bg-warning text-white mb-4">
        <div class="card-body"><%= t "admin.static_pages.category"%></div>
          <div class="card-footer d-flex align-items-center justify-content-between">
            <%= link_to t("admin.static_pages.view_details"), admin_categories_path, class: "small text-white stretched-link"%>
          <div class="small text-white"><i class="fas fa-angle-right"></i></div>
        </div>
      </div>
    </div>
    <div class="col-xl-3 col-md-6">
      <div class="card bg-success text-white mb-4">
        <div class="card-body"><%= t "admin.static_pages.order"%></div>
          <div class="card-footer d-flex align-items-center justify-content-between">
            <%= link_to t("admin.static_pages.view_details"), admin_orders_path, class: "small text-white stretched-link"%>
          <div class="small text-white"><i class="fas fa-angle-right"></i></div>
        </div>
      </div>
    </div>
    <div class="col-xl-3 col-md-6">
      <div class="card bg-danger text-white mb-4">
        <div class="card-body"><%= t "admin.static_pages.account" %></div>
          <div class="card-footer d-flex align-items-center justify-content-between">
            <%= link_to t("admin.static_pages.view_details"), admin_users_path, class: "small text-white stretched-link"%>
          <div class="small text-white"><i class="fas fa-angle-right"></i></div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xl-6">
      <div class="card mb-4">
        <div class="card-header">
          <i class="fas fa-chart-bar me-1"></i>
          <%= t "admin.static_pages.chart1" %>
        </div>
        <div class="card-body">
          <%= bar_chart bar_chart_product(@products) %>
          </div>
      </div>
    </div>
    <div class="col-xl-6">
      <div class="card mb-4">
        <div class="card-header">
          <i class="fas fa-chart-pie me-1"></i>
          <%= t "admin.sta tic_pages.chart2" %>
        </div>
        <div class="card-body">
           <%= pie_chart pie_chart_order(@orders) %>
        </div>
      </div>
    </div>
  </div>
</div>