config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#index"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/mens", to: "products#mens"
    get "/womans", to: "products#womans"
    get "sort", to: "categories#category_sort"
    devise_for :users
    resources :users, except: :destroy
    resources :account_activations, only: %i(edit create)
    resources :password_resets, except: %i(destroy index show)

    namespace :admin do
      get "search", to: "products#index"
      resources :static_pages
      resources :categories
      resources :orders
      resources :products
      resources :users
      resources :banners
      root "static_pages#index"
    end
    resources :ratings
    resources :order_details
    resources :categories do
      member do
        get :filter
      end
    end
    resources :products do
      collection do
        get :result
      end
    end
    resources :carts
    resources :orders do
      member do
        get :change
      end
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category, optional: true
  has_many :ratings, dependent: :destroy
  has_many :order_details
  has_many :orders, through: :order_details
  has_many :product_images, dependent: :destroy, inverse_of: :product
  acts_as_paranoid without_default_scope: true

  accepts_nested_attributes_for :product_images, allow_destroy: true

  delegate :name, to: :category, prefix: true

  validates :price, :quantity_in_stock, presence: true

  scope :mens, ->{where("products.category_id IN (?)", [3,5,7,9])}

  scope :womans, ->{where("products.category_id IN (?)", [4,6,8,10,11])}

  scope :by_name, (lambda do |name|
                     where("name LIKE (?)", "%#{name}%") if name.present?
                   end)
  scope :order_by_price, ->(criteria){order(price: criteria)}
  scope :find_category_id, ->(param){where category_id: param}
  scope :order_by_created_at, ->(param){order(created_at: param)}
  scope :newest, ->{order created_at: :desc}
  scope :oldest, ->{order created_at: :asc}
  scope :by_ids, ->(ids){where id: ids}
  scope :uncategorized, ->{where category_id: nil}
  scope :by_category, ->(category_id){where category_id: category_id}
  scope :cheapest, ->{order price: :asc}
  scope :most_expensive, ->{order price: :desc}
  scope :categorized, ->{where.not(category_id: nil)}

  def find_root_category parent_path
    arr = parent_path.split("/")
    return arr.second
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  before_action :find_product, only: %i(edit show update destroy)
  before_action :get_categories, only: %i(new edit show update index)

  def index
    filter_branch params
  end

  def show
    @product.product_images.build
  end

  def new
    @product = Product.new
    @product.product_images.build
  end

  def edit; end

  def update
    if @product.update(product_params)
      flash[:success] = t "flashes.update_success"
      redirect_to admin_product_path(@product)
    else
      flash[:danger] = t "flashes.update_failed"
      render :edit
    end
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = t "flashes.create_success"
      redirect_to admin_product_path(@product)
    else
      flash[:danger] = t "flashes.create_failed"
      render :new
    end
  end

  def destroy
    if @product.destroy
      flash[:success] = t "flashes.delete_success"
    else
      flash[:danger] = t "flashes.delete_failed"
    end
    redirect_to admin_products_path
  end

  private
  def find_product
    @product = Product.without_deleted.categorized.find_by id: params[:id]
    return if @product

    flash[:danger] = t "flashes.alert_not_found"
    redirect_to admin_products_path
  end

  def product_params
    params.require(:product).permit(:name, :price, :description,
                                    :quantity_in_stock, :category_id,
                                    product_images_attributes:
                                    [:id, :image, :_destroy])
  end

  def get_categories
    @categories = Category.all
  end

  def filter_branch params
    if params[:filter] == t("admin.product.filter.uncate")
      @pagy, @products = pagy(Product.without_deleted.uncategorized,
                              items: Settings.product.item)
    elsif params[:name].present?
      @pagy, @products = pagy(Product.without_deleted.where("name like ?", "%#{params[:name]}%"),
        items: Settings.product.item)
    else
      @pagy, @products = pagy(Product.without_deleted.newest,
                              items: Settings.product.item)
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include ProductsHelper

  before_action :current_visitor_selections

  def index
    @q = Product.without_deleted.categorized.ransack(params[:q])
    unless !@q.result.empty?
      flash[:danger] = "Can't find what you look for"
      redirect_to root_path
      return
    end
    @pagy, @products = pagy @q.result
  end

  def mens
    @search = Product.without_deleted.categorized.mens.ransack(params[:q])
    @pagy, @products = pagy @search.result
  end

  def womans
    @search = Product.without_deleted.categorized.womans.ransack(params[:q])
    @pagy, @products = pagy @search.result
  end

  def show
    visitor_selection(params[:id])
    @product = Product.without_deleted.categorized.find_by(id: params[:id])
    @ratings = Rating.where(product_id: params[:id])
    if current_user.present?
      @rating = current_user.ratings.build
    end
    if @product.present?
      @ratings_stats = @ratings if @ratings.present?
      @pagy, @ratings = pagy @ratings if @ratings.present?

      @same_category = @product.category.products.where.not(id: params[:id]).sample(10)
    end
    return if @product.present?

    flash[:danger] = t "static_pages.product_not_found"
    redirect_to root_path
  end

  def result
    @name = params[:name]
    @pagy, @products = pagy Product.without_deleted.categorized.by_name params[:name]
  end

  def all_product(category_id)
  end

  private

  def visitor_selection(pid)
    session[:selection] ||= []

    if !session[:selection].include? pid.to_i
      session[:selection].unshift pid.to_i
    end
  end
end

app/helpers/admin/product_helper.rb
module Admin::ProductHelper
  def category_name category_id
    category = @categories.find_by id: category_id
    category.nil? ? t("admin.category.none") : category.name
  end

  def in_category categories
    output = []
    categories.each do |cate|
      input = [cate.name, cate.id.to_s]
      output.append input
    end
    output.append ["None", ""]
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def average_star(ratings)
    sum = 0
    count = 0
    ratings.each do |rating|
      sum += rating.star.to_i
      count += 1
    end
    return sum / count
  end

  def star_statistic(ratings)
    arr = [0, 0, 0, 0, 0, 0]
    sum = 0
    ratings.each do |rating|
      case rating.star
      when 1
        arr[0] += 1
      when 2
        arr[1] += 1
      when 3
        arr[2] += 1
      when 4
        arr[3] += 1
      when 5
        arr[4] += 1
      end
      sum += rating.star
    end
    arr[5] = sum / ratings.size
    return arr
  end

  def current_visitor_selections
    session[:selection] ||= []
    @selections = session[:selection]
  end

  def allow_comment(product)
    allow = false
    product.orders.each do |order|
      if order.user_id == current_user.id
        allow = true
        break
      end
    end
    return allow
  end

  def checkout_these_product(dataset)
    session[:selection] ||= []
    recommend_pids = []
    if !current_user.nil?
      if dataset == 1 and !current_user.recommend_1.nil?
        recommend_pids = eval(current_user.recommend_1)
      elsif dataset == 2 and !current_user.recommend_2.nil?
        recommend_pids = eval(current_user.recommend_2)
      elsif dataset == 3 and !current_user.recommend_3.nil?
        recommend_pids = eval(current_user.recommend_3)
      end
    end

    if session[:selection].present?
      rules = Recommended.all
      rules.each do |rule|
        if rule.dataset == dataset.to_s
          associations = rule.associations.split("=>").map! { |id| id.to_i }
          left = []
          left << associations.first
          check = session[:selection] - left
          if check != session[:selection]
            second = []
            second << associations.second
            recommend_pids = (recommend_pids + second).uniq
          end
        end
      end
    end

    if session[:selection].present?
      session[:selection].each do |pid|
        products = Product.categorized.without_deleted.find_by(id: pid).category.products.sample(2).pluck(:id)
        recommend_pids << products
        recommend_pids.flatten!
        recommend_pids.uniq!
        if recommend_pids.size >= 15
          break
        end
      end
    end
    #-----------------------------------------------------------------------------------
    # if recommend_pids.size > 15
    #   recommend_pids = recommend_pids.take(15)
    # end
    if recommend_pids.size < 15
      take_num = 15 - recommend_pids.size
      extras = Product.categorized.without_deleted.sample(take_num).pluck(:id)
      recommend_pids << extras
    end
    recommend_pids.flatten!
    return recommend_pids
  end

  def categories_of_woman
    cate_w = []
    Category.all.each do |cate|
      if cate.parent_path.present?
        if cate.parent_path.split("/").second.to_i == 2
          cate_w << cate
        end
      end
    end
    return cate_w
  end

  def page_path current_product
    page_path = ["Homepage"]
    product_category = current_product.category.id
    parent_category = current_product.category.category.name
    page_path << parent_category << product_category
    return page_path
  end
end

app/views/products/_comment_form.html.erb
<h4>Your's comment</h4>
<%= form_for @rating do |f| %>
  <%= f.hidden_field :product_id, value: @product.id %>
  <div class="form-outline mb-4">
    <%= f.text_field :comment, type: "text" , id: "form4Example1" , class: "form-control", placeholder: "Your's comments here" %>
  </div>
  <div class="mb-4">
    <label>
      <%= f.radio_button :star, "1" %>
      <span class="icon">★</span>
    </label>
    <label>
      <%= f.radio_button :star, "2" %>
      <span class="icon">★</span>
      <span class="icon">★</span>
    </label>
    <label>
      <%= f.radio_button :star, "3" %>
      <span class="icon">★</span>
      <span class="icon">★</span>
      <span class="icon">★</span>
    </label>
    <label>
      <%= f.radio_button :star, "4" %>
      <span class="icon">★</span>
      <span class="icon">★</span>
      <span class="icon">★</span>
      <span class="icon">★</span>
    </label>
    <label>
      <%= f.radio_button :star, "5" %>
      <span class="icon">★</span>
      <span class="icon">★</span>
      <span class="icon">★</span>
      <span class="icon">★</span>
      <span class="icon">★</span>
    </label>
  </div>
  <%= f.submit "Comment", class: "btn btn-primary btn-block mb-4" %>
<% end %>

app/views/products/_image.html.erb
<% if product.product_images.any? %>
  <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <% product.product_images.includes(image_attachment: :blob).each do |proimg| %>
        <% if proimg == product.product_images.first %>
          <div class="carousel-item active">
            <%= image_tag((proimg.image), class: "d-block w-100") if proimg.image.present?%>
          </div>
        <% else %>
          <div class="carousel-item">
            <strong><%= t("admin.product.image") + product.product_images.find_index(proimg).to_s %></strong>
            <%= image_tag(proimg.thumbnail(proimg.image), class: "d-block w-100") if proimg.image.present?%>
          </div>
        <% end %>
      <% end %>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
<% end %>

app/views/products/_rating.html.erb
<tr>
  <td><%= rating.user.name %></td>
  <td><%= rating.comment %></td>
  <td><%= rating.star %></td>
</tr>

app/views/products/_related.html.erb
<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <% related.includes(image_attachment: :blob).each do |proimg| %>
      <% if proimg == product.product_images.first %>
        <div class="carousel-item active">
          <strong><%= t("admin.product.image") + product.product_images.find_index(proimg).to_s %></strong>
          <%= image_tag((proimg.image), class: "d-block w-100") if proimg.image.present? %>
        </div>
      <% else %>
        <div class="carousel-item">
          <strong><%= t("admin.product.image") + product.product_images.find_index(proimg).to_s %></strong>
          <%= image_tag(proimg.thumbnail(proimg.image), class: "d-block w-100") if proimg.image.present? %>
        </div>
      <% end %>
    <% end %>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/products/_search_bar.html.erb
<%= search_form_for @q, url: products_path, class: "d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search",
                        html: { method: :get } do |f| %>
  <div class="input-group">
    <%= f.search_field :name_cont, class: "form-control bg-light border-0 small", placeholder: "Search for..."%>
    <div class="input-group-append">
      <%= submit_tag class: "btn btn-primary" do %>
        <i class="fas fa-search fa-sm"></i>
      <% end %>
    </div>
  </div>
<% end %>

app/views/products/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <div class="dropdown-minh" style="padding-bottom: 1.5%;">
        <button class="dropbtn-minh btn btn-outline-dark">
          <%= t("static_pages.filter") %>
        </button>
        <div class="dropdown-content-minh">
          <%= sort_link(@q, :created_at, 'Newest', default_order: :asc) %>
          <%= sort_link(@q, :created_at, 'Oldest', default_order: :desc) %>
          <%= sort_link(@q, :price, 'Cheapest', default_order: :asc) %>
          <%= sort_link(@q, :price, 'Most Expensive', default_order: :desc) %>
        </div>
      </div>
    </div>
    <div class="col">
    </div>
  </div>
  <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
    <% @products.each do |p|%>
      <div class="col mb-5">
        <div class="zoom">
          <div class="card h-100">
            <div class="align-items-center justify-content-center text-center">
              <!-- Product image-->
              <%= image_tag p.product_images.first.image.variant(resize_to_fill: [200, 200]), class: "card-img-top" %>
              <!-- Product details-->
              <div class="card-body p-4">
                <div class="text-center">
                  <!-- Product name-->
                  <h5 class="fw-bolder">
                    <%= link_to p.name, product_path(p), style: "text-decoration: none; color: black;" %>
                  </h5>
                  <%= number_to_currency(p.price) %>
                </div>
              </div>
              <!-- Product actions-->
              <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                <%= form_with url: carts_path(id: p.id ), method: :post do |f| %>
                  <fieldset>
                    <%= f.hidden_field :quantily, value: 1, max: 10, min: Settings.carts.min_quantily %>
                    <input type="submit" name="submit" value="Add to cart"
                                class="btn btn-outline-dark mt-auto" />
                  </fieldset>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%== pagy_bootstrap_nav(@pagy) %>
</div>

app/views/products/mens.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-2">
        <div class="input-group mb-3">
          <%= search_form_for @search, url: mens_path, html: { method: :get } do |f| %>
            <%= f.search_field :name_cont, class: "form-control" %>
            <div>
              <h5>Category</h5>
            </div>
            <div class="mb-1">
              <%= link_to "Shirt" , mens_path(q: {"name_cont"=>"", "category_name_cont"=>"shirt", "category_eq"=>""}), class: "btn btn-outline-dark" %>
            </div>
            <div class="mb-1">
              <%= link_to "Pants" , mens_path(q: {"name_cont"=>"", "category_name_cont"=>"pants", "category_eq"=>""}), class: "btn btn-outline-dark" %>
            </div>
            <div class="mb-1">
              <%= link_to "Shoes" , mens_path(q: {"name_cont"=>"", "category_name_cont"=>"shoes", "category_eq"=>""}), class: "btn btn-outline-dark" %>
            </div>
            <div class="mb-1">
              <%= link_to "Accessories" , mens_path(q: {"name_cont"=>"", "category_name_cont"=>"accessories", "category_eq"=>""}), class: "btn btn-outline-dark" %>
            </div>
            <div>
              <h5>Price range</h5>
            </div>
            <div class="mb-1">
              <%= f.label :From%>
              <%= f.search_field :price_gteq, class: "form-control" %>
            </div>
            <div class="mb-1">
              <%= f.label :To%>
              <%= f.search_field :price_lteq, class: "form-control" %>
            </div>
            <%= f.submit "Search", class: "btn btn-outline-dark mt-2"%>
          <% end %>
        </div>
      </div>
    <div class="col-sm-10">
      <div class="container">
        <div class="row">
          <div class="col">
            <div class="dropdown-minh" style="padding-bottom: 1.5%;">
              <button class="dropbtn-minh btn btn-outline-dark">
                <%= t("static_pages.filter") %>
              </button>
              <div class="dropdown-content-minh">
                <%= sort_link(@search, :created_at, 'Newest', default_order: :asc) %>
                <%= sort_link(@search, :created_at, 'Oldest', default_order: :desc) %>
                <%= sort_link(@search, :price, 'Cheapest', default_order: :asc) %>
                <%= sort_link(@search, :price, 'Most Expensive', default_order: :desc) %>
              </div>
            </div>
          </div>
          <div class="col">
          </div>
        </div>
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
          <% @products.each do |p|%>
            <div class="col mb-5">
              <div class="zoom">
                <div class="card h-100">
                  <!-- Product image-->
                  <%= image_tag p.product_images.first.image.variant(resize_to_fill: [200, 200]), class: "card-img-top" %>
                  <!-- Product details-->
                  <div class="card-body p-4">
                    <div class="text-center">
                      <!-- Product name-->
                      <h5 class="fw-bolder">
                        <%= link_to p.name, product_path(p), style: "text-decoration: none; color: black;" %>
                      </h5>
                      <%= number_to_currency(p.price) %>
                    </div>
                  </div>
                  <!-- Product actions-->
                  <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                    <%= form_with url: carts_path(id: p.id ), method: :post do |f| %>
                      <fieldset>
                        <% if logged_in? %>
                          <%= f.hidden_field :quantily, value: 1, max: 10, min: Settings.carts.min_quantily %>
                          <input type="submit" name="submit" value="Add to cart"
                                class="btn btn-outline-dark mt-auto" />
                        <% else %>
                          <%= link_to "Add to cart" , new_user_session_path, class: "btn btn-outline-dark" %>
                        <% end %>
                      </fieldset>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
        <%== pagy_bootstrap_nav(@pagy) %>
      </div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<!-- Page path -->
<div class="container px-4 px-lg-5">
  <% paths = page_path @product %>
  <% paths.each do |path| %>
    <% if path == "Homepage" %>
      <%= link_to "Homepage", root_path, style: "text-decoration: none; color: black;" %>
      <%= ">" %>
    <% elsif path == paths.last%>
      <%= ">" %>
      <% category = Category.find(path) %>
      <%= link_to "#{category.name}", category_path(category), style: "text-decoration: none; color: black;" %>
    <% else %>
    <% if path == "Mens" %>
        <%= link_to "Mens", mens_path, style: "text-decoration: none; color: black;" %>
      <% else %>
        <%= link_to "Womans", womans_path, style: "text-decoration: none; color: black;" %>
      <% end %>
    <% end %>
  <% end %>
</div>
<!-- Product section-->
<% page_path @product %>
<div class="container px-4 px-lg-5 my-5">
  <div class="row gx-4 gx-lg-5">
    <div class="col-md-6">
      <%= render "image", product: @product %>
    </div>
    <div class="col-md-6">
      <div class="mb-1"><%= @product.category.name %></div>
      <h1 class="display-5 fw-bolder"><%= @product.name %></h1>
      <div class="fs-5 mb-5">
        <span><%= number_to_currency(@product.price) %></span>
      </div>
      <strong>Description</strong>
      <p class="lead"><%= @product.description %></p>
      <div class="d-flex">
        <%= form_with url: carts_path(id: @product.id), method: :post do |f| %>
          <fieldset>
            <%# if logged_in? %>
              <%= f.hidden_field :quantily, value: 1, max: 10, min: Settings.carts.min_quantily %>
              <input
                type="submit"
                name="submit"
                value="Add to cart"
                class="btn btn-outline-dark mt-auto"
              />
            <%# else %>
              <%#= link_to "Add to cart", new_user_session_path, class: "btn btn-outline-dark" %>
            <%# end %>
          </fieldset>
        <% end %>
      </div>
      <br>
      <% if @ratings.present? %>
      <div class="mb-1">
        <% if current_user.present? %>
          <% check = allow_comment @product %>
          <% if check %>
            <%= render "comment_form" %>
          <% end %>
        <% end %>
      </div>
      <% if @ratings_stats.present? %>
      <div class="mb-1">
        <%= render "scorecard", ratings: @ratings_stats %>
      </div>
      <% end %>
      <div class="card" style="background-color: #faf9f8; padding: 1%;">
        <span class="heading">Users comments</span>
          <table class = "table">
            <thead>
              <tr>
                <th><%= "Customer" %></th>
                <th><%= "Comment" %></th>
                <th><%= "Rating" %></th>
              </tr>
            </thead>
            <tbody>
              <%= render partial: "rating" , collection: @ratings.includes([:user]) %>
            </tbody>
          </table>
          <%== pagy_bootstrap_nav(@pagy) %>
      </div>
      <% end %>
    </div>
  </div>
</div>
<!-- Related items section--> <!-- nếu thừa thời gian muốn làm thêm phần sản
phẩm liên quan thì copy lại đoạn này từ
desktop/startbootstrap-shop-item-gh-pages/index --> <!-- Footer-->
<% unless @same_category.nil? %>
<div class="bbb_viewed">
  <div class="container">
    <div class="row">
      <div class="col">
        <div class="bbb_main_container">
          <div class="bbb_viewed_title_container">
              <h3>Same category</h3>
              <div class="bbb_viewed_nav_container">
                  <div class="bbb_viewed_nav bbb_viewed_prev"><i class="fas fa-chevron-left"></i></div>
                  <div class="bbb_viewed_nav bbb_viewed_next"><i class="fas fa-chevron-right"></i></div>
              </div>
          </div>
          <div class="bbb_viewed_slider_container">
              <div class="owl-carousel owl-theme bbb_viewed_slider">
                <% @same_category.each do |product| %>
                <% begin %>
                  <div class="owl-item">
                    <div class="bbb_viewed_item discount d-flex flex-column align-items-center justify-content-center text-center">
                      <%= image_tag product.product_images.first.image.variant(resize_to_fill: [700, 950]), class: "card-img-top" %>
                        <div class="bbb_viewed_content text-center">
                            <div style="color: black;"><%= number_to_currency(product.price, locale: :vi) %></div>
                            <%= link_to product.name, product_path(product), style: "text-decoration: none; color: black; font-weight: bold;" %>
                        </div>
                        <%= form_with url: carts_path(id: product.id), method: :post do |f| %>
                            <fieldset>
                              <% # if logged_in? %>
                                <%= f.hidden_field :quantily, value: 1, max: 10, min: Settings.carts.min_quantily %>
                                <input
                                  type="submit"
                                  name="submit"
                                  value="Add to cart"
                                  class="btn btn-outline-dark mt-auto"/>
                              <% # else %>
                                <% #= link_to "Add to cart", new_user_session_path, class: "btn btn-outline-dark" %>
                              <% # end %>
                            </fieldset>
                          <% end %>
                      </div>
                    </div>
                  <% end %>
                <% rescue %>
                  <% next %>
                <% end %>
                </div>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>
<br><br>

app/views/products/womans.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-2">
      <div class="input-group mb-3">
        <%= search_form_for @search, url: womans_path, html: { method: :get } do |f| %>
          <%= f.search_field :name_cont, class: "form-control" %>
          <div>
            <h5>Category</h5>
          </div>
          <% categories = categories_of_woman %>
          <% categories.each do |category| %>
            <div class="mb-1">
              <%= link_to "#{category.name}" , womans_path(q: {"name_cont"=>"", "category_name_cont"=>"#{category.name}", "category_eq"=>""}), class: "btn btn-outline-dark" %>
            </div>
          <% end %>
          <div>
            <h5>Price range</h5>
          </div>
          <div class="mb-1">
            <%= f.label :From%>
            <%= f.search_field :price_gteq, class: "form-control" %>
          </div>
          <div class="mb-1">
            <%= f.label :To%>
            <%= f.search_field :price_lteq, class: "form-control" %>
          </div>
          <%= f.submit "Search", class: "btn btn-outline-dark mt-2"%>
        <% end %>
      </div>
    </div>
    <div class="col-sm-10">
      <div class="container">
        <div class="row">
          <div class="col">
            <div class="dropdown-minh" style="padding-bottom: 1.5%;">
              <button class="dropbtn-minh btn btn-outline-dark">
                <%= t("static_pages.filter") %>
              </button>
              <div class="dropdown-content-minh">
                <%= sort_link(@search, :created_at, 'Newest', default_order: :asc) %>
                <%= sort_link(@search, :created_at, 'Oldest', default_order: :desc) %>
                <%= sort_link(@search, :price, 'Cheapest', default_order: :asc) %>
                <%= sort_link(@search, :price, 'Most Expensive', default_order: :desc) %>
              </div>
            </div>
          </div>
          <div class="col">
          </div>
        </div>
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
          <% @products.each do |p|%>
            <div class="col mb-5">
              <div class="zoom">
                <div class="card h-100">
                  <!-- Product image-->
                  <%= image_tag p.product_images.first.image.variant(resize_to_fill: [200, 200]), class: "card-img-top" %>
                  <!-- Product details-->
                  <div class="card-body p-4">
                    <div class="text-center">
                      <!-- Product name-->
                      <h5 class="fw-bolder">
                        <%= link_to p.name, product_path(p), style: "text-decoration: none; color: black;" %>
                      </h5>
                      <%= number_to_currency(p.price) %>
                    </div>
                  </div>
                  <!-- Product actions-->
                  <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                    <%= form_with url: carts_path(id: p.id ), method: :post do |f| %>
                      <fieldset>
                        <% if logged_in? %>
                          <%= f.hidden_field :quantily, value: 1, max: 10, min: Settings.carts.min_quantily %>
                          <input type="submit" name="submit" value="Add to cart"
                                class="btn btn-outline-dark mt-auto" />
                        <% else %>
                          <%= link_to "Add to cart" , new_user_session_path, class: "btn btn-outline-dark" %>
                        <% end %>
                      </fieldset>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
        <%== pagy_bootstrap_nav(@pagy) %>
      </div>
    </div>
  </div>
</div>